#!/bin/bash
# Cloudflare Pages 部署验证脚本

echo "🔍 Cloudflare Pages 部署验证清单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ 1. 检查 GitHub 仓库"
echo "   仓库: https://github.com/shijianus/NewYear"
echo "   分支: main"
echo "   最新提交: $(git log --oneline -1)"
echo ""

echo "✅ 2. 检查项目文件结构"
echo "   ✓ index.html (2026新版)"
echo "   ✓ old/index.html (2024原始版)"
echo "   ✓ old/js/script.js (烟花脚本)"
echo "   ✓ old/media/*.mp3 (音频文件)"
echo "   ✓ js/script.js (烟花脚本)"
echo "   ✓ LICENSE (木兰许可证 v2)"
echo ""

echo "🌐 3. Cloudflare Pages 部署检查"
echo ""
echo "   请在浏览器中访问以下 URL 并验证功能:"
echo ""
echo "   主页 (2026版):"
echo "   https://newyear-d1x.pages.dev/"
echo ""
echo "   原始版 (2024彩蛋):"
echo "   https://newyear-d1x.pages.dev/old/"
echo ""

echo "📋 功能验证清单:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "主页检查:"
echo "  [ ] 页面能正常加载"
echo "  [ ] 年份显示为 2025/2026 (自动更新)"
echo "  [ ] 倒计时正常工作"
echo "  [ ] 烟花效果自动播放"
echo "  [ ] 右下角有'✨ 回忆 2024'链接"
echo ""
echo "原始版 (/old/) 检查:"
echo "  [ ] 页面能正常加载"
echo "  [ ] 显示'2024新春祝福'相关内容"
echo "  [ ] 点击'接收祝福'后烟花播放"
echo "  [ ] 祝福文字逐字显示"
echo "  [ ] 背景音乐能播放"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "如果所有功能正常,您就可以开始进一步开发了!"
echo ""
echo "💡 提示:"
echo "- Cloudflare Pages 会自动部署 GitHub 的 main 分支"
echo "- 每次推送都会触发重新部署"
echo "- 可以在 Cloudflare Dashboard 查看部署日志"
echo ""

